#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use DI\Container;
use PGtk\Gtk\Gtk;
use Tomate\UI\Window;

/** @var Container $container */
$container = require __DIR__ . '/bootstrap/container.php';
$window = $container->get(Window::class);

$window->run();
