/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __FAKE_DOCUMENT_PORTAL_GENERATED_H__
#define __FAKE_DOCUMENT_PORTAL_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.portal.Documents */

#define FAKE_TYPE_DOCUMENTS (fake_documents_get_type ())
#define FAKE_DOCUMENTS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), FAKE_TYPE_DOCUMENTS, FakeDocuments))
#define FAKE_IS_DOCUMENTS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), FAKE_TYPE_DOCUMENTS))
#define FAKE_DOCUMENTS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), FAKE_TYPE_DOCUMENTS, FakeDocumentsIface))

struct _FakeDocuments;
typedef struct _FakeDocuments FakeDocuments;
typedef struct _FakeDocumentsIface FakeDocumentsIface;

struct _FakeDocumentsIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_add) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *arg_o_path_fd,
    gboolean arg_reuse_existing,
    gboolean arg_persistent);

  gboolean (*handle_add_full) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *arg_o_path_fds,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions);

  gboolean (*handle_add_named) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *arg_o_path_parent_fd,
    const gchar *arg_filename,
    gboolean arg_reuse_existing,
    gboolean arg_persistent);

  gboolean (*handle_add_named_full) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *arg_o_path_fd,
    const gchar *arg_filename,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions);

  gboolean (*handle_delete) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_doc_id);

  gboolean (*handle_get_mount_point) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_grant_permissions) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions);

  gboolean (*handle_info) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_doc_id);

  gboolean (*handle_list) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_id);

  gboolean (*handle_lookup) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_filename);

  gboolean (*handle_revoke_permissions) (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions);

  guint  (*get_version) (FakeDocuments *object);

};

GType fake_documents_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *fake_documents_interface_info (void);
guint fake_documents_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void fake_documents_complete_get_mount_point (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *path);

void fake_documents_complete_add (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *doc_id);

void fake_documents_complete_add_named (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *doc_id);

void fake_documents_complete_add_full (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *const *doc_ids,
    GVariant *extra_out);

void fake_documents_complete_add_named_full (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    const gchar *doc_id,
    GVariant *extra_out);

void fake_documents_complete_grant_permissions (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation);

void fake_documents_complete_revoke_permissions (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation);

void fake_documents_complete_delete (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation);

void fake_documents_complete_lookup (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *doc_id);

void fake_documents_complete_info (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    const gchar *path,
    GVariant *apps);

void fake_documents_complete_list (
    FakeDocuments *object,
    GDBusMethodInvocation *invocation,
    GVariant *docs);



/* D-Bus method calls: */
void fake_documents_call_get_mount_point (
    FakeDocuments *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_get_mount_point_finish (
    FakeDocuments *proxy,
    gchar **out_path,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_get_mount_point_sync (
    FakeDocuments *proxy,
    gchar **out_path,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_add (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fd,
    gboolean arg_reuse_existing,
    gboolean arg_persistent,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_add_finish (
    FakeDocuments *proxy,
    gchar **out_doc_id,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_add_sync (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fd,
    gboolean arg_reuse_existing,
    gboolean arg_persistent,
    GUnixFDList  *fd_list,
    gchar **out_doc_id,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_add_named (
    FakeDocuments *proxy,
    GVariant *arg_o_path_parent_fd,
    const gchar *arg_filename,
    gboolean arg_reuse_existing,
    gboolean arg_persistent,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_add_named_finish (
    FakeDocuments *proxy,
    gchar **out_doc_id,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_add_named_sync (
    FakeDocuments *proxy,
    GVariant *arg_o_path_parent_fd,
    const gchar *arg_filename,
    gboolean arg_reuse_existing,
    gboolean arg_persistent,
    GUnixFDList  *fd_list,
    gchar **out_doc_id,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_add_full (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fds,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_add_full_finish (
    FakeDocuments *proxy,
    gchar ***out_doc_ids,
    GVariant **out_extra_out,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_add_full_sync (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fds,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GUnixFDList  *fd_list,
    gchar ***out_doc_ids,
    GVariant **out_extra_out,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_add_named_full (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fd,
    const gchar *arg_filename,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_add_named_full_finish (
    FakeDocuments *proxy,
    gchar **out_doc_id,
    GVariant **out_extra_out,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_add_named_full_sync (
    FakeDocuments *proxy,
    GVariant *arg_o_path_fd,
    const gchar *arg_filename,
    guint arg_flags,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GUnixFDList  *fd_list,
    gchar **out_doc_id,
    GVariant **out_extra_out,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_grant_permissions (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_grant_permissions_finish (
    FakeDocuments *proxy,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_grant_permissions_sync (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_revoke_permissions (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_revoke_permissions_finish (
    FakeDocuments *proxy,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_revoke_permissions_sync (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    const gchar *arg_app_id,
    const gchar *const *arg_permissions,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_delete (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_delete_finish (
    FakeDocuments *proxy,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_delete_sync (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_lookup (
    FakeDocuments *proxy,
    const gchar *arg_filename,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_lookup_finish (
    FakeDocuments *proxy,
    gchar **out_doc_id,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_lookup_sync (
    FakeDocuments *proxy,
    const gchar *arg_filename,
    gchar **out_doc_id,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_info (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_info_finish (
    FakeDocuments *proxy,
    gchar **out_path,
    GVariant **out_apps,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_info_sync (
    FakeDocuments *proxy,
    const gchar *arg_doc_id,
    gchar **out_path,
    GVariant **out_apps,
    GCancellable *cancellable,
    GError **error);

void fake_documents_call_list (
    FakeDocuments *proxy,
    const gchar *arg_app_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean fake_documents_call_list_finish (
    FakeDocuments *proxy,
    GVariant **out_docs,
    GAsyncResult *res,
    GError **error);

gboolean fake_documents_call_list_sync (
    FakeDocuments *proxy,
    const gchar *arg_app_id,
    GVariant **out_docs,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
guint fake_documents_get_version (FakeDocuments *object);
void fake_documents_set_version (FakeDocuments *object, guint value);


/* ---- */

#define FAKE_TYPE_DOCUMENTS_PROXY (fake_documents_proxy_get_type ())
#define FAKE_DOCUMENTS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), FAKE_TYPE_DOCUMENTS_PROXY, FakeDocumentsProxy))
#define FAKE_DOCUMENTS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), FAKE_TYPE_DOCUMENTS_PROXY, FakeDocumentsProxyClass))
#define FAKE_DOCUMENTS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), FAKE_TYPE_DOCUMENTS_PROXY, FakeDocumentsProxyClass))
#define FAKE_IS_DOCUMENTS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), FAKE_TYPE_DOCUMENTS_PROXY))
#define FAKE_IS_DOCUMENTS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), FAKE_TYPE_DOCUMENTS_PROXY))

typedef struct _FakeDocumentsProxy FakeDocumentsProxy;
typedef struct _FakeDocumentsProxyClass FakeDocumentsProxyClass;
typedef struct _FakeDocumentsProxyPrivate FakeDocumentsProxyPrivate;

struct _FakeDocumentsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  FakeDocumentsProxyPrivate *priv;
};

struct _FakeDocumentsProxyClass
{
  GDBusProxyClass parent_class;
};

GType fake_documents_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FakeDocumentsProxy, g_object_unref)
#endif

void fake_documents_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
FakeDocuments *fake_documents_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
FakeDocuments *fake_documents_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void fake_documents_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
FakeDocuments *fake_documents_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
FakeDocuments *fake_documents_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define FAKE_TYPE_DOCUMENTS_SKELETON (fake_documents_skeleton_get_type ())
#define FAKE_DOCUMENTS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), FAKE_TYPE_DOCUMENTS_SKELETON, FakeDocumentsSkeleton))
#define FAKE_DOCUMENTS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), FAKE_TYPE_DOCUMENTS_SKELETON, FakeDocumentsSkeletonClass))
#define FAKE_DOCUMENTS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), FAKE_TYPE_DOCUMENTS_SKELETON, FakeDocumentsSkeletonClass))
#define FAKE_IS_DOCUMENTS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), FAKE_TYPE_DOCUMENTS_SKELETON))
#define FAKE_IS_DOCUMENTS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), FAKE_TYPE_DOCUMENTS_SKELETON))

typedef struct _FakeDocumentsSkeleton FakeDocumentsSkeleton;
typedef struct _FakeDocumentsSkeletonClass FakeDocumentsSkeletonClass;
typedef struct _FakeDocumentsSkeletonPrivate FakeDocumentsSkeletonPrivate;

struct _FakeDocumentsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  FakeDocumentsSkeletonPrivate *priv;
};

struct _FakeDocumentsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType fake_documents_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FakeDocumentsSkeleton, g_object_unref)
#endif

FakeDocuments *fake_documents_skeleton_new (void);


G_END_DECLS

#endif /* __FAKE_DOCUMENT_PORTAL_GENERATED_H__ */
