/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_CAIRO 1

#define HAVE_CAIRO_FREETYPE 1

#define HAVE_CAIRO_PDF 1

#define HAVE_CAIRO_PNG 1

#define HAVE_CAIRO_PS 1

#define HAVE_CAIRO_XLIB 1

#define HAVE_DIRENT_H 1

#define HAVE_FCWEIGHTFROMOPENTYPEDOUBLE 1

#define HAVE_FLOCKFILE 1

#define HAVE_FREETYPE 1

#define HAVE_GETPAGESIZE 1

#define HAVE_LIBTHAI 1

#define HAVE_STRTOK_R 1

#define HAVE_SYSCONF 1

#undef HAVE_SYSPROF

#define HAVE_SYS_MMAN_H 1

#define HAVE_TH_BRK_FIND_BREAKS 1

#define HAVE_UNISTD_H 1

#define HAVE_XFT 1

#define PANGO_BINARY_AGE 5005

#define PANGO_INTERFACE_AGE 5

#define PANGO_VERSION_MAJOR 1

#define PANGO_VERSION_MICRO 5

#define PANGO_VERSION_MINOR 50

#define _PANGO_EXTERN __attribute__((visibility("default"))) extern

