/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Define if floating-point division is compliant with IEEE 754 */
#define HAVE_IEEE_754_FLOAT_DIVISION

/* Define if isinff is available */
#define HAVE_ISINFF

/* Define if isnanf is available */
#define HAVE_ISNANF

/* Define if memalign() is available */
#define HAVE_MEMALIGN 1

/* Define if memory.h is available */
#define HAVE_MEMORY_H

/* Define if pthread.h is available */
#define HAVE_PTHREAD_H

/* Define if sincosf is available */
#define HAVE_SINCOSF

/* Define if stdbool.h is available */
#define HAVE_STDBOOL_H

/* Define if stdint.h is available */
#define HAVE_STDINT_H

/* Define if stdlib.h is available */
#define HAVE_STDLIB_H

#define _GRAPHENE_PUBLIC __attribute__((visibility("default"))) extern

