/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_CLOCK_GETTIME 1

#define HAVE_FCNTL_H 1

#define HAVE_GETTIMEOFDAY 1

#define HAVE_ISATTY 1

#define HAVE_STPCPY 1

#define HAVE_SYS_IOCTL_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_UNISTD_H 1

#define MUTEST_PUBLIC __attribute__((visibility("default"))) extern

