/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "atspi-hyperlink.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.a11y.atspi.Hyperlink */

const GDBusArgInfo atspi_hyperlink_interface__get_object_method_in_args__i_arg =
{
  -1,  /* ref count */
  (gchar *) "i",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hyperlink_interface__get_object_method_in_args[] =
{
  &atspi_hyperlink_interface__get_object_method_in_args__i_arg,
  NULL,
};

const GDBusArgInfo atspi_hyperlink_interface__get_object_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "(so)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hyperlink_interface__get_object_method_out_args[] =
{
  &atspi_hyperlink_interface__get_object_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_hyperlink_interface__get_object_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QSpiObjectReference",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_hyperlink_interface__get_object_method_annotations[] =
{
  &atspi_hyperlink_interface__get_object_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation,
  NULL,
};

const GDBusMethodInfo atspi_hyperlink_interface__get_object_method =
{
  -1,  /* ref count */
  (gchar *) "GetObject",
  (GDBusArgInfo **) atspi_hyperlink_interface__get_object_method_in_args,
  (GDBusArgInfo **) atspi_hyperlink_interface__get_object_method_out_args,
  (GDBusAnnotationInfo **) atspi_hyperlink_interface__get_object_method_annotations,
};

const GDBusArgInfo atspi_hyperlink_interface__get_uri_method_in_args__i_arg =
{
  -1,  /* ref count */
  (gchar *) "i",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hyperlink_interface__get_uri_method_in_args[] =
{
  &atspi_hyperlink_interface__get_uri_method_in_args__i_arg,
  NULL,
};

const GDBusArgInfo atspi_hyperlink_interface__get_uri_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hyperlink_interface__get_uri_method_out_args[] =
{
  &atspi_hyperlink_interface__get_uri_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_hyperlink_interface__get_uri_method =
{
  -1,  /* ref count */
  (gchar *) "GetURI",
  (GDBusArgInfo **) atspi_hyperlink_interface__get_uri_method_in_args,
  (GDBusArgInfo **) atspi_hyperlink_interface__get_uri_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_hyperlink_interface__is_valid_method_out_args__unnamed_arg0_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg0",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hyperlink_interface__is_valid_method_out_args[] =
{
  &atspi_hyperlink_interface__is_valid_method_out_args__unnamed_arg0_arg,
  NULL,
};

const GDBusMethodInfo atspi_hyperlink_interface__is_valid_method =
{
  -1,  /* ref count */
  (gchar *) "IsValid",
  NULL,  /* no in args */
  (GDBusArgInfo **) atspi_hyperlink_interface__is_valid_method_out_args,
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const atspi_hyperlink_interface_methods[] =
{
  &atspi_hyperlink_interface__get_object_method,
  &atspi_hyperlink_interface__get_uri_method,
  &atspi_hyperlink_interface__is_valid_method,
  NULL,
};

const GDBusPropertyInfo atspi_hyperlink_interface__nanchors_property =
{
  -1,  /* ref count */
  (gchar *) "NAnchors",
  (gchar *) "n",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo atspi_hyperlink_interface__start_index_property =
{
  -1,  /* ref count */
  (gchar *) "StartIndex",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo atspi_hyperlink_interface__end_index_property =
{
  -1,  /* ref count */
  (gchar *) "EndIndex",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const atspi_hyperlink_interface_properties[] =
{
  &atspi_hyperlink_interface__nanchors_property,
  &atspi_hyperlink_interface__start_index_property,
  &atspi_hyperlink_interface__end_index_property,
  NULL,
};

const GDBusInterfaceInfo atspi_hyperlink_interface =
{
  -1,  /* ref count */
  (gchar *) "org.a11y.atspi.Hyperlink",
  (GDBusMethodInfo **) atspi_hyperlink_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) atspi_hyperlink_interface_properties,
  NULL,  /* no annotations */
};

