/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "atspi-action.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.a11y.atspi.Action */

const GDBusArgInfo atspi_action_interface__get_description_method_in_args__index_arg =
{
  -1,  /* ref count */
  (gchar *) "index",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_description_method_in_args[] =
{
  &atspi_action_interface__get_description_method_in_args__index_arg,
  NULL,
};

const GDBusArgInfo atspi_action_interface__get_description_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_description_method_out_args[] =
{
  &atspi_action_interface__get_description_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__get_description_method =
{
  -1,  /* ref count */
  (gchar *) "GetDescription",
  (GDBusArgInfo **) atspi_action_interface__get_description_method_in_args,
  (GDBusArgInfo **) atspi_action_interface__get_description_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_action_interface__get_name_method_in_args__index_arg =
{
  -1,  /* ref count */
  (gchar *) "index",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_name_method_in_args[] =
{
  &atspi_action_interface__get_name_method_in_args__index_arg,
  NULL,
};

const GDBusArgInfo atspi_action_interface__get_name_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_name_method_out_args[] =
{
  &atspi_action_interface__get_name_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__get_name_method =
{
  -1,  /* ref count */
  (gchar *) "GetName",
  (GDBusArgInfo **) atspi_action_interface__get_name_method_in_args,
  (GDBusArgInfo **) atspi_action_interface__get_name_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_action_interface__get_localized_name_method_in_args__index_arg =
{
  -1,  /* ref count */
  (gchar *) "index",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_localized_name_method_in_args[] =
{
  &atspi_action_interface__get_localized_name_method_in_args__index_arg,
  NULL,
};

const GDBusArgInfo atspi_action_interface__get_localized_name_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_localized_name_method_out_args[] =
{
  &atspi_action_interface__get_localized_name_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__get_localized_name_method =
{
  -1,  /* ref count */
  (gchar *) "GetLocalizedName",
  (GDBusArgInfo **) atspi_action_interface__get_localized_name_method_in_args,
  (GDBusArgInfo **) atspi_action_interface__get_localized_name_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_action_interface__get_key_binding_method_in_args__index_arg =
{
  -1,  /* ref count */
  (gchar *) "index",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_key_binding_method_in_args[] =
{
  &atspi_action_interface__get_key_binding_method_in_args__index_arg,
  NULL,
};

const GDBusArgInfo atspi_action_interface__get_key_binding_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_key_binding_method_out_args[] =
{
  &atspi_action_interface__get_key_binding_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__get_key_binding_method =
{
  -1,  /* ref count */
  (gchar *) "GetKeyBinding",
  (GDBusArgInfo **) atspi_action_interface__get_key_binding_method_in_args,
  (GDBusArgInfo **) atspi_action_interface__get_key_binding_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_action_interface__get_actions_method_out_args__unnamed_arg0_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg0",
  (gchar *) "a(sss)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__get_actions_method_out_args[] =
{
  &atspi_action_interface__get_actions_method_out_args__unnamed_arg0_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_action_interface__get_actions_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QSpiActionArray",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_action_interface__get_actions_method_annotations[] =
{
  &atspi_action_interface__get_actions_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__get_actions_method =
{
  -1,  /* ref count */
  (gchar *) "GetActions",
  NULL,  /* no in args */
  (GDBusArgInfo **) atspi_action_interface__get_actions_method_out_args,
  (GDBusAnnotationInfo **) atspi_action_interface__get_actions_method_annotations,
};

const GDBusArgInfo atspi_action_interface__do_action_method_in_args__index_arg =
{
  -1,  /* ref count */
  (gchar *) "index",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__do_action_method_in_args[] =
{
  &atspi_action_interface__do_action_method_in_args__index_arg,
  NULL,
};

const GDBusArgInfo atspi_action_interface__do_action_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_action_interface__do_action_method_out_args[] =
{
  &atspi_action_interface__do_action_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_action_interface__do_action_method =
{
  -1,  /* ref count */
  (gchar *) "DoAction",
  (GDBusArgInfo **) atspi_action_interface__do_action_method_in_args,
  (GDBusArgInfo **) atspi_action_interface__do_action_method_out_args,
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const atspi_action_interface_methods[] =
{
  &atspi_action_interface__get_description_method,
  &atspi_action_interface__get_name_method,
  &atspi_action_interface__get_localized_name_method,
  &atspi_action_interface__get_key_binding_method,
  &atspi_action_interface__get_actions_method,
  &atspi_action_interface__do_action_method,
  NULL,
};

const GDBusPropertyInfo atspi_action_interface__nactions_property =
{
  -1,  /* ref count */
  (gchar *) "NActions",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const atspi_action_interface_properties[] =
{
  &atspi_action_interface__nactions_property,
  NULL,
};

const GDBusInterfaceInfo atspi_action_interface =
{
  -1,  /* ref count */
  (gchar *) "org.a11y.atspi.Action",
  (GDBusMethodInfo **) atspi_action_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) atspi_action_interface_properties,
  NULL,  /* no annotations */
};

