/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "atspi-hypertext.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.a11y.atspi.Hypertext */

const GDBusArgInfo atspi_hypertext_interface__get_nlinks_method_out_args__unnamed_arg0_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg0",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hypertext_interface__get_nlinks_method_out_args[] =
{
  &atspi_hypertext_interface__get_nlinks_method_out_args__unnamed_arg0_arg,
  NULL,
};

const GDBusMethodInfo atspi_hypertext_interface__get_nlinks_method =
{
  -1,  /* ref count */
  (gchar *) "GetNLinks",
  NULL,  /* no in args */
  (GDBusArgInfo **) atspi_hypertext_interface__get_nlinks_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_hypertext_interface__get_link_method_in_args__linkIndex_arg =
{
  -1,  /* ref count */
  (gchar *) "linkIndex",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hypertext_interface__get_link_method_in_args[] =
{
  &atspi_hypertext_interface__get_link_method_in_args__linkIndex_arg,
  NULL,
};

const GDBusArgInfo atspi_hypertext_interface__get_link_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "(so)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hypertext_interface__get_link_method_out_args[] =
{
  &atspi_hypertext_interface__get_link_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_hypertext_interface__get_link_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QSpiObjectReference",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_hypertext_interface__get_link_method_annotations[] =
{
  &atspi_hypertext_interface__get_link_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation,
  NULL,
};

const GDBusMethodInfo atspi_hypertext_interface__get_link_method =
{
  -1,  /* ref count */
  (gchar *) "GetLink",
  (GDBusArgInfo **) atspi_hypertext_interface__get_link_method_in_args,
  (GDBusArgInfo **) atspi_hypertext_interface__get_link_method_out_args,
  (GDBusAnnotationInfo **) atspi_hypertext_interface__get_link_method_annotations,
};

const GDBusArgInfo atspi_hypertext_interface__get_link_index_method_in_args__characterIndex_arg =
{
  -1,  /* ref count */
  (gchar *) "characterIndex",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hypertext_interface__get_link_index_method_in_args[] =
{
  &atspi_hypertext_interface__get_link_index_method_in_args__characterIndex_arg,
  NULL,
};

const GDBusArgInfo atspi_hypertext_interface__get_link_index_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_hypertext_interface__get_link_index_method_out_args[] =
{
  &atspi_hypertext_interface__get_link_index_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusMethodInfo atspi_hypertext_interface__get_link_index_method =
{
  -1,  /* ref count */
  (gchar *) "GetLinkIndex",
  (GDBusArgInfo **) atspi_hypertext_interface__get_link_index_method_in_args,
  (GDBusArgInfo **) atspi_hypertext_interface__get_link_index_method_out_args,
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const atspi_hypertext_interface_methods[] =
{
  &atspi_hypertext_interface__get_nlinks_method,
  &atspi_hypertext_interface__get_link_method,
  &atspi_hypertext_interface__get_link_index_method,
  NULL,
};

const GDBusInterfaceInfo atspi_hypertext_interface =
{
  -1,  /* ref count */
  (gchar *) "org.a11y.atspi.Hypertext",
  (GDBusMethodInfo **) atspi_hypertext_interface_methods,
  NULL,  /* no signals */
NULL,  /* no properties */
  NULL,  /* no annotations */
};

