/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "atspi-cache.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.a11y.atspi.Cache */

const GDBusArgInfo atspi_cache_interface__get_items_method_out_args__nodes_arg =
{
  -1,  /* ref count */
  (gchar *) "nodes",
  (gchar *) "a((so)(so)(so)iiassusau)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_cache_interface__get_items_method_out_args[] =
{
  &atspi_cache_interface__get_items_method_out_args__nodes_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_cache_interface__get_items_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QSpiAccessibleCacheArray",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_cache_interface__get_items_method_annotations[] =
{
  &atspi_cache_interface__get_items_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation,
  NULL,
};

const GDBusMethodInfo atspi_cache_interface__get_items_method =
{
  -1,  /* ref count */
  (gchar *) "GetItems",
  NULL,  /* no in args */
  (GDBusArgInfo **) atspi_cache_interface__get_items_method_out_args,
  (GDBusAnnotationInfo **) atspi_cache_interface__get_items_method_annotations,
};

const GDBusMethodInfo * const atspi_cache_interface_methods[] =
{
  &atspi_cache_interface__get_items_method,
  NULL,
};

const GDBusArgInfo atspi_cache_interface__add_accessible_signal_args__nodeAdded_arg =
{
  -1,  /* ref count */
  (gchar *) "nodeAdded",
  (gchar *) "((so)(so)(so)iiassusau)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_cache_interface__add_accessible_signal_args[] =
{
  &atspi_cache_interface__add_accessible_signal_args__nodeAdded_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_cache_interface__add_accessible_signal_annotations__org_qtproject__qt_dbus__qt_type_name__in0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.In0",
  (gchar *) "QSpiAccessibleCacheItem",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_cache_interface__add_accessible_signal_annotations[] =
{
  &atspi_cache_interface__add_accessible_signal_annotations__org_qtproject__qt_dbus__qt_type_name__in0_annotation,
  NULL,
};

const GDBusSignalInfo atspi_cache_interface__add_accessible_signal =
{
  -1,  /* ref count */
  (gchar *) "AddAccessible",
  (GDBusArgInfo **) atspi_cache_interface__add_accessible_signal_args,
  (GDBusAnnotationInfo **) atspi_cache_interface__add_accessible_signal_annotations,
};

const GDBusArgInfo atspi_cache_interface__remove_accessible_signal_args__nodeRemoved_arg =
{
  -1,  /* ref count */
  (gchar *) "nodeRemoved",
  (gchar *) "(so)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_cache_interface__remove_accessible_signal_args[] =
{
  &atspi_cache_interface__remove_accessible_signal_args__nodeRemoved_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_cache_interface__remove_accessible_signal_annotations__org_qtproject__qt_dbus__qt_type_name__in0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.In0",
  (gchar *) "QSpiObjectReference",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_cache_interface__remove_accessible_signal_annotations[] =
{
  &atspi_cache_interface__remove_accessible_signal_annotations__org_qtproject__qt_dbus__qt_type_name__in0_annotation,
  NULL,
};

const GDBusSignalInfo atspi_cache_interface__remove_accessible_signal =
{
  -1,  /* ref count */
  (gchar *) "RemoveAccessible",
  (GDBusArgInfo **) atspi_cache_interface__remove_accessible_signal_args,
  (GDBusAnnotationInfo **) atspi_cache_interface__remove_accessible_signal_annotations,
};

const GDBusSignalInfo * const atspi_cache_interface_signals[] =
{
  &atspi_cache_interface__add_accessible_signal,
  &atspi_cache_interface__remove_accessible_signal,
  NULL,
};

const GDBusInterfaceInfo atspi_cache_interface =
{
  -1,  /* ref count */
  (gchar *) "org.a11y.atspi.Cache",
  (GDBusMethodInfo **) atspi_cache_interface_methods,
  (GDBusSignalInfo **) atspi_cache_interface_signals,
NULL,  /* no properties */
  NULL,  /* no annotations */
};

