/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "atspi-image.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.a11y.atspi.Image */

const GDBusArgInfo atspi_image_interface__get_image_extents_method_in_args__coordType_arg =
{
  -1,  /* ref count */
  (gchar *) "coordType",
  (gchar *) "u",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_image_interface__get_image_extents_method_in_args[] =
{
  &atspi_image_interface__get_image_extents_method_in_args__coordType_arg,
  NULL,
};

const GDBusArgInfo atspi_image_interface__get_image_extents_method_out_args__unnamed_arg1_arg =
{
  -1,  /* ref count */
  (gchar *) "unnamed_arg1",
  (gchar *) "(iiii)",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_image_interface__get_image_extents_method_out_args[] =
{
  &atspi_image_interface__get_image_extents_method_out_args__unnamed_arg1_arg,
  NULL,
};

const GDBusAnnotationInfo atspi_image_interface__get_image_extents_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation =
{
  -1,  /* ref count */
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QSpiRect",
  NULL,  /* no annotations */
};

const GDBusAnnotationInfo * const atspi_image_interface__get_image_extents_method_annotations[] =
{
  &atspi_image_interface__get_image_extents_method_annotations__org_qtproject__qt_dbus__qt_type_name__out0_annotation,
  NULL,
};

const GDBusMethodInfo atspi_image_interface__get_image_extents_method =
{
  -1,  /* ref count */
  (gchar *) "GetImageExtents",
  (GDBusArgInfo **) atspi_image_interface__get_image_extents_method_in_args,
  (GDBusArgInfo **) atspi_image_interface__get_image_extents_method_out_args,
  (GDBusAnnotationInfo **) atspi_image_interface__get_image_extents_method_annotations,
};

const GDBusArgInfo atspi_image_interface__get_image_position_method_in_args__coordType_arg =
{
  -1,  /* ref count */
  (gchar *) "coordType",
  (gchar *) "u",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_image_interface__get_image_position_method_in_args[] =
{
  &atspi_image_interface__get_image_position_method_in_args__coordType_arg,
  NULL,
};

const GDBusArgInfo atspi_image_interface__get_image_position_method_out_args__x_arg =
{
  -1,  /* ref count */
  (gchar *) "x",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_image_interface__get_image_position_method_out_args__y_arg =
{
  -1,  /* ref count */
  (gchar *) "y",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_image_interface__get_image_position_method_out_args[] =
{
  &atspi_image_interface__get_image_position_method_out_args__x_arg,
  &atspi_image_interface__get_image_position_method_out_args__y_arg,
  NULL,
};

const GDBusMethodInfo atspi_image_interface__get_image_position_method =
{
  -1,  /* ref count */
  (gchar *) "GetImagePosition",
  (GDBusArgInfo **) atspi_image_interface__get_image_position_method_in_args,
  (GDBusArgInfo **) atspi_image_interface__get_image_position_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_image_interface__get_image_size_method_out_args__width_arg =
{
  -1,  /* ref count */
  (gchar *) "width",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo atspi_image_interface__get_image_size_method_out_args__height_arg =
{
  -1,  /* ref count */
  (gchar *) "height",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const atspi_image_interface__get_image_size_method_out_args[] =
{
  &atspi_image_interface__get_image_size_method_out_args__width_arg,
  &atspi_image_interface__get_image_size_method_out_args__height_arg,
  NULL,
};

const GDBusMethodInfo atspi_image_interface__get_image_size_method =
{
  -1,  /* ref count */
  (gchar *) "GetImageSize",
  NULL,  /* no in args */
  (GDBusArgInfo **) atspi_image_interface__get_image_size_method_out_args,
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const atspi_image_interface_methods[] =
{
  &atspi_image_interface__get_image_extents_method,
  &atspi_image_interface__get_image_position_method,
  &atspi_image_interface__get_image_size_method,
  NULL,
};

const GDBusPropertyInfo atspi_image_interface__image_description_property =
{
  -1,  /* ref count */
  (gchar *) "ImageDescription",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo atspi_image_interface__image_locale_property =
{
  -1,  /* ref count */
  (gchar *) "ImageLocale",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const atspi_image_interface_properties[] =
{
  &atspi_image_interface__image_description_property,
  &atspi_image_interface__image_locale_property,
  NULL,
};

const GDBusInterfaceInfo atspi_image_interface =
{
  -1,  /* ref count */
  (gchar *) "org.a11y.atspi.Image",
  (GDBusMethodInfo **) atspi_image_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) atspi_image_interface_properties,
  NULL,  /* no annotations */
};

